### ISSUE TITLE
the values in the menu entries are not executed which have spaces in them.

### ISSUE THREAD

**Issue by CoffeeCat1920** [fr33zing/fr33zmenu#3]
I am unable to execute the `lvim` entry from my `menu.toml` file using `fr33zmenu`. All other entries (e.g., `emacs`, `firefox`, `thunar`) work as expected, but when selecting `lvim`, nothing happens.

#### Menu Configuration
Here is the relevant portion of my `menu.toml`:

```toml
[menus.programs]         # Define a new menu named "programs"
order = -1               # Ensure it is the first menu
prompt = "study -> "     # Give it a custom prompt

[menus.programs.entries]  # Define the menu's entries
# ↓ Name      ↓ Value
emacs      = "emacsclient -c -a emacs"
firefox    = "firefox"
thunar     = "thunar"
lvim       = "foot lvim"  # This entry fails to execute

[menus.power]            # Another menu
prompt = "power -> "

[menus.power.entries]
shutdown = "shutdown now"
reboot   = "reboot"
```

and here is the launch script

```shell
#!/bin/sh

fr33zmenu ~/.config/fr33zmenu/menu.toml \
    --exec-with "nohup" \
    --transient
```
